### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by hdunderscore**
Basically you'll see a change to the IBLs, also some changes to the code and sample. I updated the deferred render method so that it closely matches the forward renderer. I didn't make the changes to glsl yet.

Change summary:
```
- Fixed a few errors in the BRDF functions
- Fixed the specular calculations
- Small code refactor to allow for more consistency and easier experimentation.
- Implemented the ImageSampling algorithm as described in Epic's 2013 paper, with improvements.
- Implemented a true working deferred renderer.
- Updated the concrete normal map (reversed the direction).
- Changed the sRGB setting of the diffuse textures and cubemap, to perform calculations in linear space.
- Added post-process effects to the PBR sample.```

### CODE REVIEW

**Comment by dragonCASTjosh** [comment]
Color's seam very off
screenshot_wed_apr__6_18_36_52_2016
screenshot_wed_apr__6_18_37_24_2016

**Comment by hdunderscore** [comment]
Hmm looks like in DX11, there are some big differences with the values the ImportanceSampling function is calculating.

**Comment by dragonCASTjosh** [comment]
If you get this working for both OpenGL and DirectX 11 then i will merge it as it provides much better results

**Comment by hdunderscore** [comment]
I think it worked out for the best, I noticed an issue with the old ImportanceSampleGGX function (singularity at poles) which is what was causing the DX11 build to give poor results. I've put together a simpler ImportanceSample function that in my mind just makes much more sense than the GGX version and it seems to have fewer visual issues.

There is a different issue now though, when you run the PBRSample with DX11, it gives a horrible output. I haven't figured it out yet, it seems to be related to the SPECULAR define.

**Comment by dragonCASTjosh** [comment]
You just need to fix the examples under d3d11 and port it to OpenGL

**Comment by dragonCASTjosh** [comment]
D3D11 Demos still show errors

**Comment by hdunderscore** [comment]
With the commit that I just pushed? Screenshot?

**Comment by dragonCASTjosh** [comment]
Yes im running the latest commit
pbrerror

**Comment by hdunderscore** [comment]
That's strange, the commit should have resolved that issue. Can you double check this change is in your local version:
https://github.com/dragonCASTjosh/Urho3D/pull/9/commits/e63a5d4faedb22710f28dbfdff3705fdfb3b1d22#diff-67f332ad4ea35383abfe0e01bc5a2367R39

**Comment by hdunderscore** [comment]
I think I might have fixed the issue in the new commit.

Not ready for merge yet though, still need to fix DeferredHWDepth for GL2/GL3 (I am passing on testing DeferredHWDepth for DX11, I get a random crash that I think must be an issue in master) and track down a few random issues here and there. I wish there weren't such random issues popping up :x

**Comment by hdunderscore** [comment]
Oh and btw you might notice that the GL version has a lower quality IBL, I left the PBRFAST optimisation on for GLSL because otherwise the performance was too low. I think with the right mipmap filter you might not get any artifacts with PBRFAST on. In DX11, the lod texture sample is much improved so using PBRFAST only leaves a subtle colour change, but big performance boost.

**Comment by dragonCASTjosh** [comment]
the cubemap seams are visible within opengl
screenshot_fri_apr__8_12_09_47_2016

**Comment by dragonCASTjosh** [comment]
other then that its perfect

**Comment by hdunderscore** [comment]
Yeah that's because of the PBRFAST define that I left enabled, it can be turned off to hide the seams but GL seems to perform much worse than DX.

**Comment by hdunderscore** [comment]
Does GL3 deferred renderpath show the specular spot for you? On my end it doesn't, I can't track down the issue. Also the GL2/3 DeferredHWDepth don't show any direct lights for me, I can't tell if it's an issue with the shaders or something else.

Either way I'm thinking we can merge this and see if anyone else has ideas.

**Pull request merged**
