### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by hdunderscore**
I made some minor tweaks.

I believe many see the gamma issue as a over-bright vs darks issue, where the gamma correction I applied before appears as over-bright and the uncorrected version appears better due to richer darks. The main reason for this is that the IBL isn't using HDR textures (and urho doesn't load hdr texture information atm), so for now I've added a hdr-scaling to add some fake hdr amount. You can change the zone ambient colour alpha to see the difference (1 is how it was before, >1 fakes hdr, <1 lets you dim the ibl).

As far as viewing in the editor, the simplest way atm is to open the console and type graphics.sRGB = 1. Alternatively we could append the GammaCorrection post-process to the renderpath xmls, but that won't work for forward atm. Having an option in the preferences menu makes the most sense.

### CODE REVIEW

**Comment by dragonCASTjosh** [comment]
I was trying to avoid being to set SRGB as it was the number 1 complaint i  was  given many developers didn't want to go through the extra step because it lowered productivity.

As for the other changes I'll test them

**Comment by dragonCASTjosh** [comment]
@cadaver have you voiced your opinion on the SRGB stuff?

**Comment by cadaver** [comment]
I don't have a strict opinion on it.
I'll be making my GLES-related fixes once this PR is merged to your branch.

**Comment by dragonCASTjosh** [comment]
@hdunderscore some artifacts from what id assume to be the changes in gamma correction, tested under dx11 using the sample

pbrerror2
pbrerror1

**Comment by dragonCASTjosh** [comment]
in addition to the artifacts the IBL changes alone are not physically correct and therefore the output color is wrong. although it has pointed out a issue with the outline of smooth objects

Before
screenshot_wed_jul_20_11_24_04_2016

After
screenshot_wed_jul_20_11_24_12_2016

**Comment by dragonCASTjosh** [comment]
turns out the color issue roots from the current solution :)

**Comment by hdunderscore** [comment]
Can you explain the steps you took to get the artifacts ? I saw them once earlier but haven't seen them again.

All calculations are approximate, so none of them are physically correct, only physically based :P Can you be more specific in how the changes are incorrect? I tried to search for the source of the model for comparison images, but I couldn't find it.

**Comment by hdunderscore** [comment]
@dragonCASTjosh where did you source the inverse square light calculation?

**Comment by dragonCASTjosh** [comment]
@hdunderscore  to get the artifacts i used the default cmake otions + d3d11, compiled and run the c++ pbr example.

all the BRDF and IBL are classed as physically correct according to EA Frostbite for BRDF and Epic for IBL. for the IBL the source is [https://www.unrealengine.com/blog/physically-based-shading-on-mobile](https://www.unrealengine.com/blog/physically-based-shading-on-mobile). For the BRDF  the source is [http://www.frostbite.com/wp-content/uploads/2014/11/course_notes_moving_frostbite_to_pbr.pdf](http://www.frostbite.com/wp-content/uploads/2014/11/course_notes_moving_frostbite_to_pbr.pdf)

As for the light falloff im not sure on the source because its an old implementation i had laying around from experiments, all i remember was the web page has a swinging light animation :)

**Comment by hdunderscore** [comment]
Let me know if you still get the light artifacts, I believe it was because HDR rendering wasn't enabled in that sample.

**Comment by dragonCASTjosh** [comment]
why the changes to the falloff, all it needed was a light change to make it

`
float falloff = pow(clamp(1 - pow(lightDist / 1, 4), 0.0, 1.0),2) / (pow(lightDist, 2.0) - 1.0);
`

ill also test the artifact now see if it remains

**Comment by dragonCASTjosh** [comment]
After testing, i can confirm that this solves the prior issues but creates new ones. The specular has become square and under low roughness values begins to flash

pbrerror2

**Comment by dragonCASTjosh** [comment]
Personally id prefer the gamma correction to be left as its current implementation, id like to merge the IBL stuff with a slight tweek to allow IBL brightness above 1. but the SRGB and color space stuff provided both nicer results and was easier to use when merged with PBR, it would also be easier to do small changes under GLES to correct colors in linier space.

**Comment by hdunderscore** [comment]
The bloom issues always existed, as well as specular aliasing. When you view the output without bloom, you can see it's normal.

The gamma correction as I have implemented it is correct. Double check you have loaded my PR without changes, because the screenshot you posted earlier doesn't look like mine. Look closely at my PR results and compare with texture colors, eg: The hover bike textures are orange, and in my PR render as orange-- but in your version it renderered as yellow like the pannel texture. The leather texture is pink and in my PR renders as pink, but in yours it renders as white.

I'm not sure why you claim my result is incorrect and yours is correct, your diffuse IBL missed a few tricks. The 'correct' way to do it would be to sample a pre-rendered irradiance map, but the trade-off is needing to pre-render textures and to use an extra sampler.

By the way, just to clear it up, no one implements physically 'correct' shaders, they implement physically 'based' shaders, on frostbite paper page 2:

```Throughout the R&D process, we have used `ground truth' reference|measured or rendered, as
appropriate|to evaluate the accuracy of our solutions. However, being truly physically correct is a
huge task and it is unlikely that game engines can achieve it today, given current real-time performance contraints. Therefore, where decent approximations are still possible, we favor believability over absolute correctness if it brings us closer to our image quality target.```

I'm not saying we should just make things up, but without comparisons to other implementations or real life data, we have to fallback on the basic principles of pbr such as energy conservation and correct colour space, eg: In the unmodified IBL, diffuse didn't factor in the ibl contribution, it was purely based on the diffColor input. If someone used a particularly dark zone texture, the unmodified solution would look like it's glowing in the dark.

You need to pay close attention to when and where you need to gamma correct, because you demonstrated you misunderstand. There are a few places where gamma-correction needs to be considered:

- When loading or sampling textures, eg: diffuse, zone maps. If the image source is encoded in sRGB format, you need to decode.
- When doing calculations: we assume that the inputs are already sanitized and in linear space, so we don't do gamma corrections
- When outputting lights: we want to linearly add the effects of light to the scene (eg, overlapping lights, lights + ibls, etc), so we don't gamma-correct the output here either. You could see the harsh edges around the point lights (even with inverse square falloff), when you pre-emptively gamma-corrected.
- When we are doing post-process effects, eg tonemapping: We would write new physically-based post process effects that work in linear space: no gamma correction
- When you finally output to the viewport: We want to view the colours in a nicer way, so we DO gamma correct.

You can't just make a change at a random place in the pipeline to have gamma-correction and assume that's ok. Eg, @OldSnake mentioned an issue with texture loading, but you assumed you could solve it with lighting output which isn't correct.

There is a simple rule: convert inputs (if needed) to linear space, perform calculations in linear space, convert final output to sRGB space. 

With the way we set it up now, you can choose not to do any gamma correction as long as you don't flag textures with the srgb flag. In that case textures are sampled, assumed to be linear, calculations performed, then do no gamma correction at all at the end. It might look similar, but it's not 'the way' any of the major implementations will recommend.

**Comment by dragonCASTjosh** [comment]
The images and error are from a fresh download of your branch with no changes.

In regards to reference I use Sparky (developed by an EA engine developer) and render pipeline who developer I check alot of my math with.

My final images where a little off as I forgot to multiply in the diffuse.

As for gamma correction i perform correction for each individual step, I admit it needs a little clean up so that I gamma correct brdf and not final color.

As for converting inputs most users will not need to worry about this and them who it affects likely know about it and can add the texture flags. The textures used for testing are exported form substance painter.

Most major engines automatically convert to linear color space only if needed. They they approach PBR in there own way but gamma correct each step.

**Comment by dragonCASTjosh** [comment]
Ok so the largest changes on my master should correct the diffuse color issue. And the falloff is identical to epics formula

**Comment by dragonCASTjosh** [comment]
im rereading the frostbite paper every day at this point to make as many improvements as possible as well as looking at sparky as it uses code direct from frostbite experience

**Comment by cadaver** [comment]
Ok, been thinking of the gamma correction a bit. It sounds wasteful to perform correction at each step, and it's not ideal if this can never be disabled. To compare: srgb flag in textures can be set on/off, and user can choose to include or not include the gamma correction postprocess at the end, depending on what parts of the rendering pipeline they want linear or not.

Therefore I'd suggest defining the gamma-correction-each-step as a shader compile flag, so user can also choose to disable it.

**Comment by dragonCASTjosh** [comment]
@cadaver the reason to perform it at each step is to allow users to tweek each stage, the only steps in PBR that will need correction are the BRDF and the IBL. that said even with gamma correction at the end IBL should also perform its own correction in addition to the final stage.

That said i have bee experimenting a little with correction at the last stage before outputting from the main shaders and here are the results.

Before:
screenshot_thu_jul_21_20_50_34_2016

After:
screenshot_thu_jul_21_20_51_00_2016

After /W hdunderscores IBL changes:
screenshot_thu_jul_21_20_53_08_2016

**Comment by dragonCASTjosh** [comment]
The only reason that the rest of the pipeline does not need correcting is because its not physically accurate, the color output of these stage already match the correct output color the engine expects, whilst the physically accurate steps are not gamma correct for the output so they are the only 2 stages that need corrections, i also ensured that i performed the low performance correction of a simple pow(x, 1.0/2.2)

**Comment by cadaver** [comment]
I would say that there really isn't a color space that the engine "expects", since it's really a dumb toolbox / pipeline that the user can quite freely configure. It just happens that the default you get out-of-the-box (no postprocesses, no srgb textures / rendertargets) is everything happening in gamma space, which isn't ideal for correct results.

**Comment by dragonCASTjosh** [comment]
without needing to rebuild the whole shader pipeline to work with the same color space as PBR it create inaccurate results to correct everything at the end, as you say everything happens to be in gamma space and therefore look uniform and correct as an output. 

as a separate point have you considered turning the "dumb toolbox" into a structured well pipeline

**Comment by cadaver** [comment]
I personally like the way Urho is structured and how it's quite configurable, and doesn't limit or assume usecases. E.g. the default shaders are completely replaceable if the user is knowledgeable enough.

**Comment by dragonCASTjosh** [comment]
i mean more of a cleanup whats there to make it less like a mess of diffrent users code and more uniform and structured. it may make it easier for users to add features if each step is clearly defined e.g render pipline has each stage in its own shader. 

back on topic i can work on adding manual control for the BRDF correction and with the IBL changes in this PR there is control to handle IBL, not technically gamma correction but it seams to create the right output.

**Comment by hdunderscore** [comment]
I'm withdrawing from this topic as it's going in circles. The way gamma is handled in this PR is correct, and can be verified with a quick google search on shader linear colour space / srgb issues etc.

**Comment by dragonCASTjosh** [comment]
@hdunderscore I'm not saying your correction is wrong math wise, what I'm saying is only the brdf and possibly the ibl need gamma correcting

**Comment by dragonCASTjosh** [comment]
If you just PR the ibl changes will merge it seperate

**Comment by hdunderscore** [comment]
Here is the simplest explanation I can come up with to describe why gamma encoding the outputs in the lighting shaders isn't the way:

Let's assume all our inputs are handled correctly, we loaded everything so that it's in a linear space. Since we have got everything loaded into linear space, we now have to gamma encode the output at some point. If we don't do that, then the image will look strange on our monitors.

Each fragment we calculate lighting for each light individually and the ibl base pass, and they are added together. We could call the result of the sum ```lightSumFragment```, and each result: ```light1Result```, ```light2Result``` etc, and ```iblResult```.

If we gamma encode the lighting output in the lighting shader (and ibl), then this is what we are doing:
```
float3 lightSumFragment = pow(light1Result, 1.0/2.2) + pow(light2Result, 1.0/2.2) + pow(iblResult, 1.0/2.2)
```
We are adding all the lights and ibl in a non-linear way. That's not what you want to do.

What we want to do is this:
```
float3 lightSumFragment = light1Result + light2Result + iblResult;
float3 postProcessGammaEncode = pow(lightSumFragment, 1.0 / 2.2);
```
If you keep the lighting shaders without pre-emptive gamma-encoding, that's what we will get. We do the sums, then in the post-process (or with graphics.sRGB = true) we encode at last.

We made an assumption earlier, that we have loaded everything in linear space correctly. This is another topic worthy of a wall-of-text, but I'm keeping simple.

The real question is 'what is the problem you are trying to solve'. With this, we can come towards a better solution. Is it to be able to preview the output in the editor without graphics.sRGB=true? Is it to avoid having to enable the srgb=true flag for textures?

**Comment by hdunderscore** [comment]
Your screenshots of my PR always seem off, so here are screenshots of my PR in action when viewed with the appropriate gamma correction, and unaltered:
screenshot_fri_jul_22_21_51_36_2016
screenshot_fri_jul_22_21_52_41_2016

**Comment by dragonCASTjosh** [comment]
> The real question is 'what is the problem you are trying to solve'. With this, we can come towards a better solution. Is it to be able to preview the output in the editor without graphics.sRGB=true? Is it to avoid having to enable the srgb=true flag for textures?

I want to solve both, i want ability to view PBR in the editor as if it was the default renderer by this i mean not needing to go out your way to make it work. This would involve both not setting SRGB in the editor and not setting flags on textures.

As for the screenshots i believe there may be some issue it may not be easy to replicate as i even built your repo on my laptop with no prior urho version installed and still had the same issue in the.example.

**Comment by dragonCASTjosh** [comment]
can i also note that if you look at the low roughness balls that have a texture color there is something playing weird with the diffuse brightness compared to the specular (last image, right side, last line of balls)

**Comment by dragonCASTjosh** [comment]
In the editor when setting srgb i get the same results as the images but its the demo that does not work correctly

**Comment by cadaver** [comment]
Though, the only way to get multiple lights to accumulate correctly in a physically-based fashion is to gamma-correct only once at the end, right?

It would be fairly trivial to add a checkbox to the editor that adds the gamma correction postprocess.

**Comment by dragonCASTjosh** [comment]
@cadaver could you do a chckbox for PBR that selects the PBR version of the current render path along with enabling sRGB or the gamma correction post process

**Comment by cadaver** [comment]
There isn't a prepass PBR or forward PBR renderpath though, only deferred PBR with and without hwdepth. There already is the selector field for renderpath, so I'd rather not attach automagic processes to it. Also, the user might also want to use gamma correction for reasons that have nothing to do with PBR, so therefore just having a gamma correction checkbox is more flexible.

**Comment by dragonCASTjosh** [comment]
fair enough.

i also think the main issue with the demo is the bloom, i recommend we disables it. as for the diffuse vs specular issue i mentioned earlier im not sure whats causing it but ill take a look after this get merged.

before merging are we going to remove the texture xml stuff and just leave it to the gamma correction post processing

**Comment by cadaver** [comment]
The postprocess toggle is in Urho3D master branch.

**Comment by dragonCASTjosh** [comment]
ill merge it and see about fixing the issues with the diffuse power i think i know what i could be.

**Comment by hdunderscore** [comment]
When you push some changes to master, I'll resubmit a new PR to get this code updated. I saw you made some other changes that will interfere with the gamma correction.

As for the texture xmls, the srgb flag should still remain true for the diffuse texture. We could add a Texture [xml] Editor into the Editor, that will let us easily tick some boxes to auto-generate the texture xmls.

**Comment by dragonCASTjosh** [comment]
merged although i want to look into the diffuse stuff i mentioned.

**Pull request merged**
