### PR TITLE
Tweaks2

### PR DESCRIPTION
**Pull request by hdunderscore**
> - Removed inconsistency with roughness input.
> - Switched to a different mip map selection method for the IBL.
> - Extended the angelscript PBR sample to include a slider for ambient HDR scaling.
> - Removed an extra diffuse factor in lighting output.

The major visual differences are the diffuse factor change (which was causing diffuse to burn out) and the mip selection. The mip selection change brings the appearance of the IBL closer to the direct lighting (eg, surfaces that appear rough in direct light should also appear rough in the IBL).

### CODE REVIEW

**Comment by dragonCASTjosh** [comment]
i was looking to remove the extra diffuse but it looks like you have done it for me. ill merge and let cadaver know

**Comment by dragonCASTjosh** [comment]
@hdunderscore after more testing im not a fan of the changes to the mip map selection, it causes 80% of materials to be rough compared to a nice pow2 curve as it was prior


Before:
screenshot_sun_jul_24_23_39_13_2016

After:
screenshot_sun_jul_24_23_39_21_2016

**Comment by dragonCASTjosh** [comment]
i have reverted that change for now

**Comment by hdunderscore** [comment]
This is why I changed it:

Original IBL only (no direct light):
screenshot_mon_jul_25_18_49_22_2016

In this screenshot, the materials all look a little shiny, if not very shiny.

Direct light only (no IBL):
screenshot_mon_jul_25_18_50_05_2016

In this screenshot, the materials all have a clearer sense of roughness. 

In concept, you should be able to get the same sense of material properties from the IBL and direct lights.

Here is IBL only with my variation (roughness * roughness):
screenshot_mon_jul_25_18_58_03_2016

For these materials at least, it gives a more aligned result. The numbers chosen for the gloss bias and scale are tweaked to match the direct light, without any specific reason other than visual appearance.

We don't have to change it, it really comes down to another case of design materials for the shader.

**Comment by hdunderscore** [comment]
Actually I want to correct myself on that last line, the material design wouldn't change the unaligned nature of the direct light vs IBL calculation in this case. Although differences in the way you pre-filter the zone texture might make change the result.

**Comment by dragonCASTjosh** [comment]
im not sure what the issue is there as the original mip selection should be correct as it creates the desired roughness curve (looking at the roughness and metallic example materials. but when it comes to the pre-exported materials it look off. i kinda want to put this done to the materials themself but i cant be sure on it. if you can find a way to fix this without changing the current roughness curve that would be great. worst case we can change the roughness value

**Comment by hdunderscore** [comment]
It could be many things, although at the moment I'm not able to comb through the theory to track down a perfectly accurate solution with explanation.

The mipselect change only affects the IBL roughness appearance, it doesn't have a wide of impact on the rest of the shader.

The original method doesn't stand out to me as something that is particularly accurate either (unless you specifically pre-filter your zone texture to have a direct roughness-mip method, but I'm not sure that [modified]cubemapgen gives that as an option).

**Comment by dragonCASTjosh** [comment]
the cubemap in use is pre-filtered with 9 mip levels although i also tested with unfiltered mips. Most filtering software are designed around the roughness<sup>2</sup> approach

unreal use the following code for there mip selection, i will give this a test.

```
 half ComputeCubemapMipFromRoughness( half Roughness, half MipCount )
 {
	// Level starting from 1x1 mip
	half Level = 3 - 1.15 * log2( Roughness );
	return MipCount - 1 - Level;
 }
```

**Comment by dragonCASTjosh** [comment]
the PR was merged but, if you submit any changes i recommend disabling bloom on the examples and set the zone alpha color to 1

**Pull request merged**
